scenario_env_json: /mnt/sda/AdvFuzz/src/settings/scenario_env.json
output_path: /mnt/sda/AdvFuzz/src/outputs/advfuzz # absolute path
lgsvl_map: SanFrancisco_correct
apollo_map: SanFrancisco_correct
scenario: roadway

pop_size: 4
npc_size: 4
time_size: 10
bounds: [[[0,4],[0,4]],[[0,4],[0,150]],[[0,1],[0,9]]]
# bounds2: [[[0,2],[0,2]],[[0,2],[0,150]],[[0,1],[0,9]]]
total_sim_time: 40
p_mutation: 0.4
p_crossover: 0.4
max_gen: 300
selection: roulette

# apollo reltaed path config
default_record_folder: /mnt/sda/apollo/data/bag # /home/cmf/apollo/apollo6.0/apollo/data/bag # False means ignoring records